### ISSUE TITLE
Sprint 1 Complete

### ISSUE THREAD

**Issue by wangela** [Look-ARound/LookARound#20]
- [x] Issue #13 by @hallmont 
- [x] Issue #14 by @sijiracheltom 
- [x] Issues #15 and #17 by @alimir1 
- [x] Isseue #18 by @wangela

**Comment by wangela** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Push Sprint 1 walkthrough gif and submit to CodePath](https://trello.com/c/WuUERx0c/12-push-sprint-1-walkthrough-gif-and-submit-to-codepath)
